apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: https://github.com/Vishwas1976/argo.git
    targetRevision: HEAD
    path: argocd/theApps/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
