apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-1-deployment
  labels:
    app: dev-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-app-1
  template:
    metadata:
      labels:
        app: dev-app-1
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
